### ISSUE TITLE
Pubmed parser exception with latest pubmed xml format

### ISSUE THREAD

**Issue by Monika-Mistry** [Rothamsted/ondex-knet-builder#12]
Using the pubmed parser in ondex-mini throws this exception:

`org.codehaus.stax2.typed.TypedXMLStreamException: ParseError at [row,col]:[696,43]
Message: Element content can not contain child START_ELEMENT when using Typed Access methods
        at com.ctc.wstx.sr.BasicStreamReader._constructTypeException(BasicStreamReader.java:5475)
        at com.ctc.wstx.sr.BasicStreamReader._constructUnexpectedInTyped(BasicStreamReader.java:5468)
        at com.ctc.wstx.sr.BasicStreamReader.getElementText(BasicStreamReader.java:705)
        at net.sourceforge.ondex.parser.medline2.xml.XMLParser.parseMedlineCitation(XMLParser.java:282)
        at net.sourceforge.ondex.parser.medline2.xml.XMLParser.parse(XMLParser.java:246)
        at net.sourceforge.ondex.parser.medline2.xml.XMLParser.parseMedlineXML(XMLParser.java:131)
        at net.sourceforge.ondex.parser.medline2.Parser.start(Parser.java:101)
        at net.sourceforge.ondex.workflow.engine.Engine.runParser(Engine.java:433)
        at net.sourceforge.ondex.workflow.engine.PluginProcessor$5.run(PluginProcessor.java:135)
        at net.sourceforge.ondex.workflow.engine.PluginProcessor$5.run(PluginProcessor.java:133)
        at net.sourceforge.ondex.workflow.engine.PluginProcessor.execute(PluginProcessor.java:83)
        at net.sourceforge.ondex.workflow.engine.BasicJobImpl.run(BasicJobImpl.java:110)
        at net.sourceforge.ondex.WorkflowMain.main(WorkflowMain.java:216)
        at net.sourceforge.ondex.OndexMiniMain.main(OndexMiniMain.java:7)`

Here's a sample file in the latest pubmed xml format: [pubmed_test.zip](https://github.com/Rothamsted/ondex-knet-builder/files/1829176/pubmed_test.zip)

**Comment by AjitPS** [comment]
FYI, occurring due to the _new_ html formatting tags (e.g., `<i>, <sub>, <sup>`) now found within `AbstractText` blocks in the XML (_retrieved by the `eFetch web service`_) which cause the `stax` xml parser (at ../modules/textmining/../parser/medline2/xml/ ) to throw an exception.

**Comment by marco-brandizi** [comment]
The XML attached above is truncated and hence I cannot test your use case. Please give me a correct copy of it, then I can go ahead with the first investigation I was trying to do, which is fixing the wrong syntax that PUBMED seems to be outputting by wrapping HTML fragments with [CDATA](https://en.wikipedia.org/wiki/CDATA). So, the test is replacing `<ArticleTitle>` with `<ArticleTitle><![CDATA[`,  `</ArticleTitle>` with `]]></ArticleTitle> and the same for `AbstractText` (no other tags seems to contain HTML tags. If the plug-in works with the XML fixed this way, then, as the final solution, I would propose to simply preprocess the XML with some bash/sed scripting (I can write the script after this verification).

**Comment by AjitPS** [comment]
FYI, @Monika-Mistry has the complete XML files

**Comment by Monika-Mistry** [comment]
A new test dataset with 2 publications 
[pubmed_result.zip](https://github.com/Rothamsted/ondex-knet-builder/files/1837296/pubmed_result.zip)

**Comment by marco-brandizi** [comment]
I've added the CDATA wrapping. Please try the new ONDEX at the download page and let me know, so that we can close this issue.
